[workspace]

members = [
	"pabitell-lib",
	"pabitell-cli",
	"stories/doggie_and_kitie/cake/",
	"stories/doggie_and_kitie/doll/",
	"pabitell-root",
]

default-members = [
	"pabitell-lib",
]

exclude = []
