[package]
name = "pabitell-lib"
version = "0.1.0"
authors = ["Stepan Henek"]
edition = "2018"

[dependencies]
anyhow = "1"
fluent = { version = "~0.15.0", optional = true }
fluent-bundle = { version = "~0.15.0", optional = true }
fluent-langneg = { version = "~0.13.0", optional = true }
include_dir = { version = "~0.6.1", optional = true  }
intl-memoizer = { version = "~0.5.1", optional = true }
unic-langid = { version = "~0.9.0", features = ["macros"], optional = true }
uuid = "0.8"

[features]
default = []
with_translations = [
	"fluent",
	"fluent-bundle",
	"fluent-langneg",
	"include_dir",
	"intl-memoizer",
	"unic-langid",
]
with_world_setup = []

[dev-dependencies]
uuid = { version = "0.8", features = ["v4"] }
