narrator = Narrator
qr_code = QR code
qr_code_scan = Scan QR code to perform an action.
event = Event
restart = Play again
end = End.
last_stories = Last stories
no_camera = Selected camera is not available
built_on = Built on
will_join_the_game = {$characterName} will join the game.
