[build]
target = "index.html"
# Build in release mode.
release = false
# The output dir for all final assets.
dist = "dist/"
# The public URL from which assets are to be served.
public_url = "/"

[watch]
# Paths to watch, defaults to build target parent folder.
path = ["src"]
# Paths to ignore.
ignore = []

[serve]
# The port to serve on.
port = 8080
# Open a browser tab once the initial build is complete.
open = false

[clean]
# The output dir for all final assets.
dist = "dist/"
# Optionally perform a cargo clean.
cargo = false

[[proxy]]
backend = "http://localhost:8081/api/"

[[proxy]]
backend = "ws://localhost:8081/ws/"
ws = true
