narrator = Vypravěč
qr_code = QR kód
qr_code_scan = Naskenuj QR kód aby se mohla provést akce.
event = Událost
restart = Pustit znovu
end = Konec.
last_stories = Poslední příběhy
no_camera = Vybraná kamera není dostupná
built_on = Sestaveno
will_join_the_game = {$characterName} se připojí ke hře.
not_json = Nahraný soubor není v JSON formátu.
wrong_json = Formát nahraného souboru není platný.
world_editor = Editor příběhu
places = Místa
navigate = Naviguj
