[package]
name = "pabitell-cli"
version = "0.1.0"
edition = "2018"

[features]
default = []
with_doggie_and_kitie = [
	"with_doggie_and_kitie_cake"
]
with_doggie_and_kitie_cake = ["doggie_and_kitie_cake"]

[dependencies]
anyhow = "1"
pabitell-lib = { path = "../pabitell-lib/", features = ["with_translations"] }
uuid = { version = "0.8", features = ["serde"]}
skim = "0.9"
sled = "0.34"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
doggie_and_kitie_cake = { path = "../stories/doggie-and-kitie/cake/", optional = true }
